"""test2

Revision ID: b684573d1951
Revises: a325d11f6f70
Create Date: 2023-01-27 03:00:22.287753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b684573d1951'
down_revision = 'a325d11f6f70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email_id', table_name='user')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('email_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mobile_number', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('hashed_passcode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('mobile_number', name='user_mobile_number_key')
    )
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_index('ix_user_email_id', 'user', ['email_id'], unique=False)
    # ### end Alembic commands ###
